<?php
/**
 * AllCatholicMedia — Cache Clearer (no terminal needed)
 * Upload to public/ on cPanel, visit: /dev/public/acm-clear.php?key=acm2026fix
 * DELETE this file immediately after use.
 */

define('SECRET', 'acm2026fix');
if (($_GET['key'] ?? '') !== SECRET) {
    http_response_code(403);
    die('Forbidden. Add ?key=acm2026fix to the URL.');
}

header('Content-Type: text/plain; charset=utf-8');

$baseDir = dirname(__DIR__);

echo "=== AllCatholicMedia Cache Clearer ===\n\n";

// Directories of cached files to wipe
$cacheDirs = [
    'bootstrap/cache'                => $baseDir . '/bootstrap/cache',
    'storage/framework/cache/data'   => $baseDir . '/storage/framework/cache/data',
    'storage/framework/views'        => $baseDir . '/storage/framework/views',
    'storage/framework/sessions'     => $baseDir . '/storage/framework/sessions',
];

foreach ($cacheDirs as $label => $dir) {
    if (!is_dir($dir)) {
        echo "  SKIP (not found): $label\n";
        continue;
    }

    $files   = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS)
    );
    $deleted = 0;
    $failed  = 0;
    foreach ($files as $file) {
        if ($file->isFile() && $file->getFilename() !== '.gitignore') {
            if (@unlink($file->getPathname())) {
                $deleted++;
            } else {
                $failed++;
            }
        }
    }
    echo "  $label — deleted=$deleted failed=$failed\n";
}

// Recreate the services.php and packages.php cache files Laravel needs
$bootstrapCache = $baseDir . '/bootstrap/cache';
foreach (['services.php', 'packages.php'] as $file) {
    $path = $bootstrapCache . '/' . $file;
    if (!file_exists($path)) {
        // These will be regenerated by Laravel on next request — just ensure dir is writable
    }
}

echo "\nDone. All caches cleared.\n";
echo "Refresh your site — Laravel will rebuild the caches automatically.\n";
echo "DELETE this file now!\n";
